/* Shift + drag 框选；复制时仅带走选中设备和选中设备之间的链路。 */
icon=function(t){if(t==='router')return '<span class="router-symbol"><b></b><b></b><i></i><i></i><i></i></span>';if(t==='camera')return '<span class="camera-symbol"><b></b><i></i></span>';if(t==='nvr')return '<span class="nvr-symbol"><b></b><i></i><i></i><i></i><i></i></span>';return `<span class="glyph ${t}">${icons[t]}</span>`};
document.querySelectorAll('.device-icon .glyph.camera,.device-icon .glyph.nvr').forEach(e=>e.outerHTML=icon(e.classList.contains('camera')?'camera':'nvr'));render();
let selectionOrigin=null,selectionRect=null,topologyClipboard=null;
function setSelection(ids){selectedIds=new Set(ids);document.querySelectorAll('.node').forEach(el=>el.classList.toggle('selected',selectedIds.has(el.id)))}
canvas.addEventListener('pointerdown',e=>{if(!e.shiftKey||e.target!==canvas)return;selectionOrigin={x:e.offsetX,y:e.offsetY};selectionRect=document.createElement('div');selectionRect.className='selection-rect';selectionRect.style.left=selectionOrigin.x+'px';selectionRect.style.top=selectionOrigin.y+'px';canvas.append(selectionRect);canvas.setPointerCapture(e.pointerId);e.preventDefault()});
canvas.addEventListener('pointermove',e=>{if(!selectionOrigin)return;const x=Math.min(selectionOrigin.x,e.offsetX),y=Math.min(selectionOrigin.y,e.offsetY),w=Math.abs(e.offsetX-selectionOrigin.x),h=Math.abs(e.offsetY-selectionOrigin.y);Object.assign(selectionRect.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'})});
canvas.addEventListener('pointerup',e=>{if(!selectionOrigin)return;const x1=Math.min(selectionOrigin.x,e.offsetX),x2=Math.max(selectionOrigin.x,e.offsetX),y1=Math.min(selectionOrigin.y,e.offsetY),y2=Math.max(selectionOrigin.y,e.offsetY);const ids=nodes.filter(n=>n.x+52>=x1&&n.x+52<=x2&&n.y+42>=y1&&n.y+42<=y2).map(n=>n.id);selectionRect.remove();selectionRect=null;selectionOrigin=null;setSelection(ids);toast(ids.length?`已框选 ${ids.length} 个设备，可按 Ctrl+C 复制`:'未选中设备')});
document.addEventListener('keydown',e=>{const editable=['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName);if(editable||!(e.ctrlKey||e.metaKey))return;if(e.key.toLowerCase()==='c'){if(!selectedIds.size)return;const picked=nodes.filter(n=>selectedIds.has(n.id));topologyClipboard={nodes:clone(picked),links:clone(links.filter(l=>selectedIds.has(l.from)&&selectedIds.has(l.to)))};e.preventDefault();toast(`已复制 ${picked.length} 个设备及内部链路`)}if(e.key.toLowerCase()==='v'&&topologyClipboard){e.preventDefault();const map=new Map(),created=topologyClipboard.nodes.map(n=>{const id=uid();map.set(n.id,id);return {...clone(n),id,x:n.x+32,y:n.y+32,name:n.name+'（副本）'}});nodes.push(...created);links.push(...topologyClipboard.links.map(l=>({...l,from:map.get(l.from),to:map.get(l.to)})));render();setSelection(created.map(n=>n.id));ui();snap();toast('已粘贴设备与链路')}});

